### ISSUE TITLE
:SearchVisualText fails if '$' is present in selected text

### ISSUE THREAD

**Issue by benwoodward** [voldikss/vim-search-me#7] opened 2019-03-02 10:53 UTC
To reproduce this, try visually-selecting any of the following text including the includes the `$` and it will not work. 

```
[[ "${BASH_SOURCE[0]}" == "${0}" ]] && trap 'cleanup "${?}" "${LINENO}" "${BASH_LINENO}" "${BASH_COMMAND}" $(printf "::%s" ${FUNCNAME[@]:-})' EXIT && main "${@:-}"
```

**Comment by voldikss** [comment] 2019-03-02 11:50
@benwoodward Thank you for reporting this bug. I have reproduced this on my PC.

Since I use `xdg-open [args]` command to open browser and search, so if there are any shell operators (such as brackets, $ .etc) in the text, the plugin will not work.

Furthermore, it will behavior differently between **zsh** and **bash**...

Unfortunately I am not familiar with shell language, so I have no idea to solve it at this moment. Let this issue be opened here, this bug will be fixed as soon as I find the solution.

**Comment by benwoodward** [comment] 2019-03-02 21:57
Thanks @voldikss for the work you've done on this plugin. 

I want to see if I can fix it myself, what's the best way to log out the value of `l:url`, `l:cmd` and `l:text` at various points in [`function! s:Search(text, search_engine)`](https://github.com/voldikss/vim-search-me/blob/a56b56ad3bcbd938e17e110ba325bf2b1fb32ad0/autoload/searchme.vim#L6)

**Comment by voldikss** [comment] 2019-03-03 00:28
I usually use `echom` to echo the value of the variable and the line number. I don't know any better way to debug vimL...

**Comment by voldikss** [comment] 2019-05-23 02:39
@benwoodward Sorry for the late fix. 

I just add a backslash `\` to escape `$`. Now in my laptop this issue has gone and I can open and search that sentence. Could you update to have a test and give me the feedback?

**Comment by benwoodward** [comment] 2019-05-24 02:41
Great! Yes, this fixes the issue I described. Thanks. 

Discovered another issue.. it looks like spaces are being double url-encoded, a space ends up as %2520 in the search param: `https://www.google.com/search?q=%2520$%7BBASH_SOURCE` (`%25` is a url-encoded `%`).

Resulting in a search for `%20${BASH_SOURCE`

**Comment by voldikss** [comment] 2019-05-24 04:37
Thanks for your test and feedback!
I reproduced several issues caused by `` ` ``, `'`, `"`, `\n`, `\` and fixed them.
You may upgrade and have a test.

**Closed** 2019-06-06 03:27 UTC
Labels: bug
